/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gridgui;

//import grid.Grid;
import citygen.BuildingTile;
import citygen.MapGridTest;
import citygen.PieceType;
import citygen.RoadBuilder;
import citygen.StreetPack;
import citygen.Tile;
import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import schematic.ClassicNotSupportedException;
import schematic.ParseException;
import schematic.Schematic;
import schematic.SchematicWriter;

//import citygen.MapGrid;
/**
 *
 * @author Daddy
 */
public class GridGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewTry
     */
    public GridGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new gridgui.GridMapPane();
        jButtonGenerate = new javax.swing.JButton();
        jTextXSize = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextYSize = new javax.swing.JTextField();
        jButtonResize = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jTextScale = new javax.swing.JTextField();
        jButtonZoom = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonGenBuildings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jButtonGenerate.setText("Gen Roads");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        jTextXSize.setColumns(3);
        jTextXSize.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextXSize.setText("20");

        jLabel1.setText("X");

        jTextYSize.setColumns(3);
        jTextYSize.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextYSize.setText("20");

        jButtonResize.setText("Resize");
        jButtonResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResizeActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTextScale.setColumns(3);
        jTextScale.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextScale.setText("20");

        jButtonZoom.setText("Zoom");
        jButtonZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZoomActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save...");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonGenBuildings.setText("Gen Buildings");
        jButtonGenBuildings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenBuildingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextXSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextYSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButtonResize))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonZoom))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave))
                    .addComponent(jButtonGenerate)
                    .addComponent(jButtonGenBuildings))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextXSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextYSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenerate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenBuildings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        // TODO add your handling code here:
        RoadBuilder roadBuilder = new RoadBuilder();
        myPane = (GridMapPane) jPanel1;
        roadBuilder.setStart(myPane.map, 5, 5);
        roadBuilder.genRoads(myPane.map);
        myPane.repaint();
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jButtonResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResizeActionPerformed
        myPane = (GridMapPane) jPanel1;
        int newX = Integer.parseInt(jTextXSize.getText());
        int newY = Integer.parseInt(jTextXSize.getText());
        myPane.resizeMap(newX, newY);
    }//GEN-LAST:event_jButtonResizeActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        myPane = (GridMapPane) jPanel1;
        myPane.map.resetMap();
        myPane.buildings.resetUsages();
        myPane.repaint();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZoomActionPerformed
        myPane = (GridMapPane) jPanel1;
        int newScale = Integer.parseInt(jTextScale.getText());
        myPane.rescaleMap(newScale);
    }//GEN-LAST:event_jButtonZoomActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(GridGUI.this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            myPane = (GridMapPane) jPanel1;

            // Put together the street pack (this needs to be more automated
            StreetPack streets = new StreetPack();
            streets.setFilename(PieceType.CORNER, "streets/dstreet-corner.schematic");
            streets.setFilename(PieceType.TEE, "streets/dstreet-tee.schematic");
            streets.setFilename(PieceType.STRAIGHT, "streets/dstreet-straight.schematic");
            streets.setFilename(PieceType.CROSS, "streets/dstreet-cross.schematic");
            streets.setFilename(PieceType.END, "streets/dstreet-end.schematic");
            streets.scale = mapscale;
            streets.fillEmpty = 0;
            streets.fillEmptyBlock = 2; // Dirt

            Schematic guiSchematic = new Schematic(myPane.map.xsize * mapscale, myPane.map.ysize * mapscale, 191);
            guiSchematic.Allocate();

            streets.layStreets(myPane.map, guiSchematic, 0);

            for (int i = 0; i < myPane.map.usedTileList.size(); i++) {
                BuildingTile bTile = myPane.map.usedTileList.get(i);
                Schematic bSchematic = bTile.building.getSchematic();
                int numRots = bTile.numberCWRotations();
                for (int rot = 0; rot < numRots; rot++) {
                    bSchematic.rotXY();
                }
                guiSchematic.insertSchematic(bTile.x1 * 10, bTile.y1 * 10, 0, bSchematic);
            }

            try {
                SchematicWriter.writeSchematicsFile(guiSchematic, file.getCanonicalPath());
            } catch (IOException | ClassicNotSupportedException | ParseException ex) {
                Logger.getLogger(MapGridTest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonGenBuildingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenBuildingsActionPerformed
        myPane = (GridMapPane) jPanel1;
        while (myPane.map.isFull() == false) {
            Tile curEmptyTile = myPane.map.getLargestEmptyTile();
            BuildingTile newBuildingTile = myPane.buildings.findMatchingBuilding(curEmptyTile);
            myPane.map.allocateTile(newBuildingTile);
        }
        myPane.map.printTiles();
        myPane.repaint();
    }//GEN-LAST:event_jButtonGenBuildingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //myGrid = new Grid(20,20);
        myPane = (GridMapPane) jPanel1;
//        myPane.map = myGrid;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GridGUI().setVisible(true);
                System.out.print("WOO");
            }
        });
    }
    //static Grid myGrid;
    static GridMapPane myPane;
    static int mapscale = 10;
    //static MapGrid myMapGrid;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenBuildings;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonResize;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonZoom;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextScale;
    private javax.swing.JTextField jTextXSize;
    private javax.swing.JTextField jTextYSize;
    // End of variables declaration//GEN-END:variables
}
